// Offline regression checks. All network calls are intercepted; no production records change.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { JSDOM, VirtualConsole } from 'jsdom';
import { transform } from 'esbuild';
const root=path.resolve(import.meta.dirname,'..');
const read=f=>fs.readFileSync(path.join(root,'public',f),'utf8');
const html=read('index.html');
assert(!/[\x00-\x08\x0B\x0C\x0E-\x1F]/.test(html),'No corrupted control characters');
const sourceDom=new JSDOM(html);
for(const script of sourceDom.window.document.querySelectorAll('script')){
  if(script.src){const p=new URL(script.src,'https://storewell.test').pathname;assert(fs.existsSync(path.join(root,'public',p)),`Local script exists: ${p}`);continue;}
  if(script.type==='module')await transform(script.textContent,{loader:'js'});
  else new vm.Script(script.textContent);
}
for(const f of ['bridge-room.js','command-deck.js','notifications.js','sw.js','staff.bundle.js',...fs.readdirSync(path.join(root,'public/vendor')).filter(f=>f.endsWith('.js')).map(f=>'vendor/'+f)]) new vm.Script(read(f));
for(const f of ['storewell-command-deck.webp','storewell-bridge-panorama.webp','command-deck.css','manifest.json'])assert(fs.statSync(path.join(root,'public',f)).size>0,f);
assert(html.includes('this.buildScene()')&&html.includes('buildZone9()'),'Complete property model is restored');
async function verifyContext(noGpu){
const logs=[], requests=[];
const vc=new VirtualConsole();vc.on('jsdomError',e=>logs.push(e.message));vc.on('error',e=>logs.push(String(e)));
const dom=new JSDOM(html,{url:'https://storewell.test/',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});
const w=dom.window;
const modelRequests=[];
const ctx=new Proxy({measureText:t=>({width:String(t).length*9}),createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}}),getImageData:()=>({data:new Uint8ClampedArray(4)})},{get:(o,k)=>k in o?o[k]:()=>{}});
w.HTMLCanvasElement.prototype.getContext=function(){return ctx;};w.HTMLCanvasElement.prototype.toDataURL=()=>'';
w.matchMedia=q=>({matches:false,addEventListener(){}});w.alert=()=>{};
w.EventSource=class{addEventListener(){}close(){}};
w.fetch=async(url,opts={})=>{requests.push({url:String(url),opts});return {ok:true,json:async()=>({E5:'blue',E8:'white',G1:'red',D1:'flashgreen',E10:'purple'}),text:async()=>html};};
w.AbortSignal.timeout=()=>undefined;
for(const f of ['vendor/three.min.js','vendor/OrbitControls.js','vendor/CSS3DRenderer.js','vendor/react.production.min.js','vendor/react-dom.production.min.js'])w.eval(read(f));
// Parse the actual bundled character geometry, skeletons and animations; stub image decoding only.
w.TextDecoder=TextDecoder;w.TextEncoder=TextEncoder;
w.URL.createObjectURL=()=> 'blob:offline-model-texture';w.URL.revokeObjectURL=()=>{};
w.THREE.TextureLoader.prototype.load=function(url,onLoad){const t=new w.THREE.Texture();setTimeout(()=>onLoad(t),0);return t;};
w.eval(read('vendor/GLTFLoader.js'));
const ModelLoader=w.THREE.GLTFLoader;
w.THREE.GLTFLoader=class extends ModelLoader{load(url,onLoad,progress,onError){modelRequests.push(url);try{const bytes=fs.readFileSync(path.join(root,'public',new URL(url,'https://storewell.test').pathname));this.parse(new w.Uint8Array(bytes).buffer,'/',onLoad,onError);}catch(e){onError?.(e);}}};
w.eval(read('exterior-characters.js'));
w.eval(read('exterior-controls.js'));
// A software DOM cannot create a GPU context; keep real scene geometry and stub only rendering.
let renderers=0;
w.THREE.WebGLRenderer=class{constructor(){renderers++;if(noGpu)throw new Error('GPU context unavailable');this.domElement=w.document.createElement('canvas');this.shadowMap={};}setPixelRatio(){}setSize(){}render(){}dispose(){}};
w.eval(read('vendor/dc-runtime.js'));
await new Promise(resolve=>setTimeout(resolve,200));
const app=w.__swApp;
assert(app,'Original property application boots');
assert(app.scene?.isScene,'Original Three.js scene exists');
assert.equal(app._webglAvailable,!noGpu,'GPU availability is recorded independently of inventory');
assert(Object.keys(app._locks||{}).length>=160,'Property has the full unit inventory');
console.log('Size catalog entries without a modeled door:',Object.keys(app._unitSize()).filter(k=>!app._locks[k]).join(', ')||'none');
assert.equal(app._statusOf('G2'),'green');
assert.equal(app._statusLabel('green'),'Rented');
assert.equal(app._statusOf('E5'),'blue');
assert.equal(app._statusOf('E8'),'white');
w._swApplyLook();await new Promise(resolve=>setTimeout(resolve,30));
assert(app.walker._modelObj?.isGroup,'Recovered GLB character replaces the primitive body');
assert(app.walker._mixer,'Recovered character animation mixer starts');
assert(modelRequests.some(url=>url.endsWith('Soldier.glb')),'Default character is the newer Soldier model');
assert.deepEqual(Object.keys(w._SWMODELS).filter(k=>['soldier','robot','xbot','cesium'].includes(k)).sort(),['cesium','robot','soldier','xbot']);
w.localStorage.setItem('sw_char',JSON.stringify({shirt:'#123456'}));
assert.equal(w._swGetChar().model,'soldier','Old saved clothing does not strand the player on the old primitive character');
assert.equal(w._swGetChar().shirt,'#123456','Saved character preferences remain intact');
assert(app._computePath({x:0,z:10},{x:0,z:-100}).length>=2,'Recovered navigation can route around the buildings');
assert(app._locks.G2.doorMat&&app._locks.G2.frame,'Unit G2 retains the newer alert material and no-lock frame');
console.log('Doors without door-frame metadata:',Object.values(app._locks).filter(rec=>!rec.doorMat||!rec.frame).map(rec=>rec.label).join(', '));
w.eval(read('bridge-room.js'));
w.eval(read('command-deck.js'));
await new Promise(resolve=>setTimeout(resolve,50));
assert.equal(w.__swDeckVisible,false,'The storage property opens first');
assert.equal(w.document.querySelector('#sw-deck').hidden,true,'The command room is hidden outside');
assert.equal(renderers,1,'Only the original property renderer is attempted before room entry');
assert.equal(app.mode,'walk','The original outdoor walking view is selected');
assert(app._siteWalls.length>30,'Outdoor plan uses actual model building edges');
if(noGpu)assert.equal(w.document.querySelector('#sw-property-fallback').hidden,false,'No-GPU startup is the outdoor property plan');
assert.equal(app._statusOf('E10'),'purple','The upgraded Ready status remains purple');
assert.equal(app._overrides.E10,'purple','Compatibility does not rewrite stored statuses');
const click=s=>{const el=w.document.querySelector(s);assert(el,s);el.dispatchEvent(new w.MouseEvent('pointerdown',{bubbles:true,button:0}));el.dispatchEvent(new w.MouseEvent('pointerup',{bubbles:true,button:0}));el.click();};
let adminSession=false;w.__swCheckLogin=()=>adminSession?'Offline admin':null;w.__swLoginGate=async()=>null;
const enter=async()=>{
  if(noGpu)click('[data-property="command"]');
  else {const entry=w.document.querySelector('#sw-cmd-tab');assert(entry,'Recovered outdoor Command Center tab');entry.click();}
  await new Promise(resolve=>setTimeout(resolve,10));
};
await enter();assert.equal(w.__swDeckVisible,false,'Unauthenticated visitors cannot enter the command bridge');
adminSession=true;app.state.editMode=true;w._swAuth={currentUser:{uid:'offline'}};
w._swRef=(db,key)=>key;w._swOnValue=(key,onValue)=>{assert.equal(key,'lockLog');onValue({val:()=>({one:{label:'G2',from:'Rented',to:'Locked out',who:'Offline admin',t:123,type:'lock'}})});return ()=>{};};
await enter();assert.equal(w.__swDeckVisible,true,'Outdoor entry opens the command room');
assert.equal(renderers,1,'The bridge uses GPU-independent 3D geometry');
assert(w.document.querySelectorAll('.bridge-surface').length>80,'Room has separate walls, floor and furniture');
if(noGpu)assert.equal(w.document.querySelector('#sw-property-fallback').hidden,true,'Outdoor fallback is hidden inside');
click('[data-action="exit"]');assert.equal(w.__swDeckVisible,false,'Exit returns outside');
await enter();assert.equal(renderers,1,'Room re-entry reuses its existing renderer');
click('[data-action="find"]');
assert.equal(w.document.activeElement.id,'deck-dialog-title','Opening inventory focuses its heading, so the phone keyboard stays closed');
assert(w.document.querySelector('#sw-deck-dialog').open,'Command windows open in a dialog independent of the 3D room');
assert(w.document.querySelectorAll('.unit-grid .unit').length>=160,'Find unit lists full catalog');
const search=w.document.querySelector('#deck-find');search.value='c11-2';search.dispatchEvent(new w.Event('input'));
assert.equal(w.document.querySelectorAll('.unit-grid .unit').length,1,'Search normalizes hyphens');
click('[data-unit="C112"]');
assert(w.document.querySelector('#deck-dialog-title').textContent.replace(/[-\s]/g,'').includes('C112'),w.document.querySelector('#deck-dialog-title').textContent);
adminSession=false;app.state.editMode=false;
const before=requests.filter(r=>r.opts.method&&r.opts.method!=='GET').length;
click('#deck-edit');await new Promise(resolve=>setTimeout(resolve,0));
assert.equal(requests.filter(r=>r.opts.method&&r.opts.method!=='GET').length,before,'Unauthenticated UI cannot write');
click('#deck-locate');adminSession=true;app.state.editMode=true;
assert.equal(w.__swDeckVisible,false,'Find on property exits command room');
if(noGpu){
  assert.equal(w.document.querySelector('#sw-property-fallback').hidden,false,'Find returns to outdoor plan');
  assert.equal(w.document.querySelectorAll('[data-plan-unit]').length,Object.keys(app._locks).length,'Property plan preserves every modeled unit');
  assert.equal(w.document.querySelector('.plan-unit.selected').dataset.planUnit,'C112','Plan highlights the searched unit');
  assert(w.document.querySelector('.bridge-log-wall')&&w.document.querySelector('.bridge-roster-wall'),'Lock activity and every unit have wall stations');
  assert(w.document.querySelector('.joystick-pad'),'Joystick remains available without WebGL');
}else assert(app._marker?.visible,'Unit location marker appears in original model');
await enter();assert.equal(w.__swDeckVisible,true,'Can return to command room');
click('[data-action="green"]');assert(w.document.querySelector('#deck-dialog-title').textContent==='Rented');
assert([...w.document.querySelectorAll('.unit-grid .unit span')].every(e=>e.textContent==='Rented'));
click('.close-dialog');
for(const filter of ['all','green','black','red','flashred','flashgreen','blue','yellow','purple']){
  click(`[data-action="${filter}"]`);
  const shown=[...w.document.querySelectorAll('[data-unit]')].map(el=>el.dataset.unit);
  const expected=Object.keys(app._locks).filter(id=>filter==='all'||app._statusOf(app._locks[id].label)===filter);
  assert.deepEqual(shown.sort(),expected.sort(),`The ${filter} dashboard button opens the correct inventory`);click('.close-dialog');
}
for(const filter of ['flashred','flashgreen']){click(`[data-action="route-${filter}"]`);assert(w.document.querySelector('#deck-dialog-title').textContent.endsWith('route'),'Each Route button opens its matching route');click('.close-dialog');}
click('[data-action="route-flashgreen"]');click('.unit-grid .unit');assert.equal(w.__swDeckVisible,false,'A route opens the marked property location');click('[data-next]');click('[data-done]');await new Promise(r=>setTimeout(r,20));assert.equal(w.__swDeckVisible,true,'Route Done returns to the bridge');
click('[data-action="install"]');assert(w.document.querySelector('#deck-dialog-title').textContent==='Install StoreWell');click('.close-dialog');
let installOpened=false;const installEvent=new w.Event('beforeinstallprompt',{cancelable:true});installEvent.prompt=async()=>{installOpened=true;};w.dispatchEvent(installEvent);click('[data-action="install"]');await new Promise(r=>setTimeout(r,0));assert(installOpened,'Install button uses the available browser install prompt');
click('[data-action="alerts"]');assert(w.document.querySelector('.toast').textContent.includes('does not support'),'Unsupported alert browsers receive a visible explanation');
w.Notification=function(){};let alertOpened=false;w.__swBellTap=()=>{alertOpened=true;};click('[data-action="alerts"]');await new Promise(r=>setTimeout(r,0));assert(alertOpened,'Alerts opens the existing notification controls');
click('[data-action="report"]');
let downloaded=false;const oldAnchorClick=w.HTMLAnchorElement.prototype.click;w.HTMLAnchorElement.prototype.click=function(){downloaded=this.download.startsWith('storewell-inventory-')&&this.href.startsWith('blob:');};click('#deck-download');assert(downloaded,'Download inventory produces a CSV download');w.HTMLAnchorElement.prototype.click=oldAnchorClick;
let staffReportOpened=false;w.__swSaveReport=()=>{staffReportOpened=true;};click('#deck-staff-report');await new Promise(r=>setTimeout(r,0));assert(staffReportOpened,'Staff report opens the existing report workflow');
click('[data-action="find"]');click('[data-unit="G2"]');
const savedStatusFn=app.setStatus;let selectedStatus;app.setStatus=async(label,state)=>{selectedStatus={label,state};return false;};click('#deck-edit');await new Promise(r=>setTimeout(r,0));click('[data-status="black"]');await new Promise(r=>setTimeout(r,0));assert.deepEqual(selectedStatus,{label:'G2',state:'black'});assert(!w.document.querySelector('[data-status="black"]').disabled,'A rejected status save re-enables the status buttons for retry');
app.setStatus=async(label,state)=>{app._overrides.G2=state;return true;};click('[data-status="black"]');await new Promise(r=>setTimeout(r,0));assert(w.document.querySelector('.dialog-body').textContent.includes('Out of service'),'A confirmed status save refreshes the unit details');delete app._overrides.G2;app.setStatus=savedStatusFn;
click('.close-dialog');click('[data-action="report"]');assert(w.document.querySelector('#deck-download'));
click('.close-dialog');click('[data-view="room"]');assert(!w.document.querySelector('#sw-deck').classList.contains('screen-focused'));
click('[data-view="desk"]');assert(w.document.querySelector('.mobile-dock .command-screen'),'Desktop Main screen opens flat, readable controls');
assert(w.document.querySelector('.bridge-joystick').hidden,'Movement controls do not cover the focused screen');
click('[data-view="room"]');
Object.defineProperty(w,'innerWidth',{configurable:true,value:393});w.dispatchEvent(new w.Event('resize'));
assert(Number(w.document.querySelector('#sw-deck').dataset.bridgeFov)<=80,'Portrait phone uses a normal lens instead of an extreme ceiling-dominated view');
assert(!w.document.querySelector('.mobile-dock .command-screen'),'Phone bridge starts in the room without covering it');
click('[data-view="desk"]');assert(w.document.querySelector('.mobile-dock .command-screen'),'Main screen gives the phone a readable focused display');
click('[data-view="room"]');assert(!w.document.querySelector('.mobile-dock .command-screen'),'Bridge restores the display to the room');
const deck=w.document.querySelector('#sw-deck'),startZ=Number(deck.dataset.bridgeZ);
w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'s',bubbles:true}));
await new Promise(resolve=>setTimeout(resolve,220));
w.document.dispatchEvent(new w.KeyboardEvent('keyup',{key:'s',bubbles:true}));
assert(Number(deck.dataset.bridgeZ)>startZ+.2,'WASD actually translates the camera through the bridge');
const stoppedZ=Number(deck.dataset.bridgeZ);await new Promise(resolve=>setTimeout(resolve,90));
assert.equal(Number(deck.dataset.bridgeZ),stoppedZ,'Releasing a movement key stops walking');
const pad=w.document.querySelector('.joystick-pad');assert(pad,'Analog joystick replaces individual direction buttons');assert.equal(w.document.querySelectorAll('[data-move]').length,0);
pad.getBoundingClientRect=()=>({left:20,top:500,width:120,height:120});
const pointer=(type,x,y,id=1)=>{const event=new w.MouseEvent(type,{clientX:x,clientY:y,bubbles:true,button:0});Object.defineProperty(event,'pointerId',{value:id});pad.dispatchEvent(event);};
const beforeJoy=Number(deck.dataset.bridgeZ);pointer('pointerdown',80,520);await new Promise(r=>setTimeout(r,200));pointer('pointerup',80,520);
assert(Number(deck.dataset.bridgeZ)<beforeJoy-.3,'Pushing the joystick forward moves through the room');
const afterJoy=Number(deck.dataset.bridgeZ);await new Promise(r=>setTimeout(r,80));assert.equal(Number(deck.dataset.bridgeZ),afterJoy,'Joystick release stops movement');
const yawBefore=Number(deck.dataset.bridgeYaw);pointer('pointerdown',119,560);await new Promise(r=>setTimeout(r,160));pointer('pointercancel',119,560);
assert(Number(deck.dataset.bridgeYaw)<yawBefore-.1,'Joystick steers like the outdoor joystick');
const yawAfter=Number(deck.dataset.bridgeYaw);await new Promise(r=>setTimeout(r,80));assert.equal(Number(deck.dataset.bridgeYaw),yawAfter,'Pointer cancellation stops turning');
// Phone look stays near eye level, with independent look and joystick fingers.
const look=(type,x,y,id=2)=>{const event=new w.MouseEvent(type,{clientX:x,clientY:y,bubbles:true,button:0});Object.defineProperty(event,'pointerId',{value:id});deck.dispatchEvent(event);};
look('pointerdown',200,300);look('pointermove',200,-2000);await new Promise(r=>setTimeout(r,40));
assert(Number(deck.dataset.bridgePitch)<=.22,'Looking up cannot strand the camera staring at the ceiling');
const beforeBoth=Number(deck.dataset.bridgeYaw);pointer('pointerdown',80,520);look('pointermove',260,-2000);pointer('pointerup',80,520);look('pointermove',290,-2000);look('pointerup',290,-2000);await new Promise(r=>setTimeout(r,40));
assert(Number(deck.dataset.bridgeYaw)<beforeBoth-.2,'A joystick finger does not cancel the separate look finger');
const beforeLevel={x:deck.dataset.bridgeX,z:deck.dataset.bridgeZ,yaw:deck.dataset.bridgeYaw};click('.level-view');
assert.equal(Number(deck.dataset.bridgePitch),0,'Level view straightens the camera');
assert.deepEqual({x:deck.dataset.bridgeX,z:deck.dataset.bridgeZ,yaw:deck.dataset.bridgeYaw},beforeLevel,'Level view preserves location and heading');
click('[data-view="room"]');const arrowZ=Number(deck.dataset.bridgeZ);
w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowUp',bubbles:true}));await new Promise(r=>setTimeout(r,180));w.document.dispatchEvent(new w.KeyboardEvent('keyup',{key:'ArrowUp',bubbles:true}));
assert(Number(deck.dataset.bridgeZ)<arrowZ-.4,'Up arrow walks forward');assert(Math.abs(Number(deck.dataset.bridgePitch))<.05,'Up arrow never tilts the camera');
pointer('pointerdown',80,520);w.dispatchEvent(new w.Event('blur'));const blurZ=deck.dataset.bridgeZ;await new Promise(r=>setTimeout(r,80));assert.equal(deck.dataset.bridgeZ,blurZ,'Losing focus stops a held joystick');
pointer('pointerdown',80,520);click('[data-action="find"]');const modalZ=deck.dataset.bridgeZ;await new Promise(r=>setTimeout(r,80));assert.equal(deck.dataset.bridgeZ,modalZ,'Opening a dialog stops movement');click('.close-dialog');
click('[data-view="room"]');w._swWalkSpd=.5;
w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'w',bubbles:true}));await new Promise(r=>setTimeout(r,3100));w.document.dispatchEvent(new w.KeyboardEvent('keyup',{key:'w',bubbles:true}));
assert(Number(deck.dataset.bridgeZ)<-20&&Number(deck.dataset.bridgeZ)>-21.51,'A clear central aisle reaches the command screen and collision stops at the wall');w._swWalkSpd=0;
click('[data-view="room"]');w._swWalkSpd=.5;w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'s',bubbles:true}));await new Promise(r=>setTimeout(r,350));w.document.dispatchEvent(new w.KeyboardEvent('keyup',{key:'s',bubbles:true}));
assert(Number(deck.dataset.bridgeZ)<12.01,'The command chair stops movement through its solid base');
w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'d',bubbles:true}));await new Promise(r=>setTimeout(r,350));w.document.dispatchEvent(new w.KeyboardEvent('keyup',{key:'d',bubbles:true}));
w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'s',bubbles:true}));await new Promise(r=>setTimeout(r,500));w.document.dispatchEvent(new w.KeyboardEvent('keyup',{key:'s',bubbles:true}));
assert(Number(deck.dataset.bridgeX)>3&&Number(deck.dataset.bridgeZ)>16,'Walking around furniture can reach the rear of the room');w._swWalkSpd=0;
click('[data-view="history"]');assert.equal(w.document.querySelector('#deck-dialog-title').textContent,'Lock activity history');
assert(w.document.querySelector('[data-lock-history-state]').textContent.includes('1 saved changes'),'Existing admin session loads actual lock history automatically');assert(!w.document.querySelector('[data-full-lock-history]').textContent.includes('sign in'),'History does not request another sign-in');click('.close-dialog');
click('[data-view="room"]');assert(!w.document.querySelector('.mobile-dock .command-screen'),'Bridge overview remains spatial on phones');
// Two-finger zoom works over the main-board tiles without activating a tile or tilting the camera.
const touch=(type,x,y,id,target=deck)=>{const event=new w.MouseEvent(type,{clientX:x,clientY:y,bubbles:true,cancelable:true,button:0});Object.defineProperties(event,{pointerId:{value:id},pointerType:{value:'touch'}});target.dispatchEvent(event);};
const tile=w.document.querySelector('[data-action="all"]'),beforePinch={x:deck.dataset.bridgeX,z:deck.dataset.bridgeZ,yaw:deck.dataset.bridgeYaw,pitch:deck.dataset.bridgePitch};
touch('pointerdown',150,250,21,tile);touch('pointerdown',250,250,22,tile);touch('pointermove',350,250,22);
assert(Number(deck.dataset.bridgeZoom)>1.8,'Spreading two fingers zooms toward the board');tile.click();assert(w.document.querySelector('#sw-deck-dialog').hidden,'A pinch never accidentally opens an inventory tile');
touch('pointermove',225,250,22);assert(Number(deck.dataset.bridgeZoom)<1,'Bringing two fingers together zooms out');
assert.deepEqual({x:deck.dataset.bridgeX,z:deck.dataset.bridgeZ,yaw:deck.dataset.bridgeYaw,pitch:deck.dataset.bridgePitch},beforePinch,'Pinch changes magnification without moving or tilting the player');
touch('pointercancel',150,250,21);touch('pointerup',225,250,22);
touch('pointerdown',200,300,23);touch('pointermove',270,300,23);touch('pointerup',270,300,23);await new Promise(r=>setTimeout(r,30));
assert(Number(deck.dataset.bridgeYaw)<Number(beforePinch.yaw)-.1,'Single-finger looking resumes after a pinch is cancelled');
touch('pointerdown',200,300,24,tile);touch('pointerup',200,300,24,tile);tile.click();assert(!w.document.querySelector('#sw-deck-dialog').hidden,'The next deliberate tap opens its window normally');
const beforeWindowClose={x:deck.dataset.bridgeX,z:deck.dataset.bridgeZ,yaw:deck.dataset.bridgeYaw};
click('.expand-dialog');assert(w.document.querySelector('#sw-deck-dialog').classList.contains('is-expanded'),'A command window can expand');
w.document.querySelector('#sw-deck-dialog').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
assert(w.document.querySelector('#sw-deck-dialog').hidden);assert.deepEqual({x:deck.dataset.bridgeX,z:deck.dataset.bridgeZ,yaw:deck.dataset.bridgeYaw},beforeWindowClose,'Closing a window does not reset the room or move the camera');
click('[data-view="room"]');assert.equal(Number(deck.dataset.bridgeZoom),1,'Bridge restores normal magnification');
assert.equal(w.document.querySelectorAll('.bridge-observation .space-scene').length,10,'All exterior wall panels have space behind observation glass');
assert([...w.document.querySelectorAll('.bridge-window')].every(el=>el.querySelector('.space-stars')),'Every forward window also has moving space');
// The rear doorway opens two leaves, permits passage, and retains the outdoor location.
const doorLocation=app.walker.g.position.clone();
click('[data-station="door"]');assert.equal(deck.dataset.bridgeDoor,'opening');assert.equal(w.document.querySelectorAll('.airlock-leaf').length,2);assert(w.document.querySelector('.airlock-trigger').disabled,'Door waits for its opening animation before exit');
await new Promise(r=>setTimeout(r,810));assert.equal(deck.dataset.bridgeDoor,'open');click('[data-station="door"]');assert.equal(w.__swDeckVisible,false,'Tapping the open doorway returns to the property');assert(app.walker.g.position.equals(doorLocation));
await enter();assert.equal(deck.dataset.bridgeDoor,'closed','Re-entering resets the doorway');
w._swWalkSpd=.5;
w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'d',bubbles:true}));await new Promise(r=>setTimeout(r,560));w.document.dispatchEvent(new w.KeyboardEvent('keyup',{key:'d',bubbles:true}));
w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'s',bubbles:true}));await new Promise(r=>setTimeout(r,750));w.document.dispatchEvent(new w.KeyboardEvent('keyup',{key:'s',bubbles:true}));
assert(['opening','open'].includes(deck.dataset.bridgeDoor),'Approaching the doorway opens it automatically');await new Promise(r=>setTimeout(r,800));
w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'s',bubbles:true}));await new Promise(r=>setTimeout(r,750));w.document.dispatchEvent(new w.KeyboardEvent('keyup',{key:'s',bubbles:true}));w._swWalkSpd=0;
assert.equal(w.__swDeckVisible,false,'Walking through the open doorway exits the room');assert(app.walker.g.position.equals(doorLocation),'The animated exit preserves the outdoor position');await enter();
// A remembered app login restores full control without showing another credential form.
const loginSource=fs.readFileSync(path.join(root,'src/staff.js'),'utf8');
const loginStart=loginSource.indexOf('window.__swCheckLogin=function(){');
const loginEnd=loginSource.indexOf('window.__swAdminSave=',loginStart);
const savedCheck=w.__swCheckLogin,savedGate=w.__swLoginGate;
w.eval(loginSource.slice(loginStart,loginEnd));
w.localStorage.setItem('sw_user','Mike');app.state.editMode=false;
await w.__swLoginGate(app);assert.equal(app.state.editMode,true);assert.equal(app.state.staffName,'Mike');assert(!w.document.querySelector('#sw-login-overlay'),'Remembered admin login does not open another sign-in form');
w.__swCheckLogin=savedCheck;w.__swLoginGate=savedGate;
// Run the retained staff panel with fake identity and network. No production data is read or written.
const staff=fs.readFileSync(path.join(root,'src/staff.js'),'utf8');
w.eval(staff.slice(staff.indexOf('window.__swOperationsOpen='),staff.indexOf('window.__swAdminOpen=')));
let signedIn=false;w.__swCheckLogin=()=>signedIn?'Offline test':null;
w.__swLoginGate=async()=>null;
click('[data-action="gear"]');click('[data-setting="log"]');
await new Promise(resolve=>setTimeout(resolve,10));
assert(!w.document.querySelector('#sw-cmd-panel'),'Cancelled staff sign-in keeps activity log closed');
signedIn=true;app.state.editMode=true;
click('[data-action="gear"]');click('[data-setting="log"]');
await new Promise(resolve=>setTimeout(resolve,20));
assert.equal(w.document.querySelector('#sw-tab-log').style.display,'block','Gear opens the retained Activity log');
click('#sw-panel-close');click('[data-action="gear"]');click('[data-setting="contacts"]');
await new Promise(resolve=>setTimeout(resolve,20));
assert.equal(w.document.querySelector('#sw-tab-contacts').style.display,'block','Gear opens the retained Team tools');
assert.equal(w.document.querySelectorAll('#sw-contact-cards [data-field="email"]').length,3,'All original team contact forms remain');
click('#sw-panel-close');click('[data-action="gear"]');click('[data-setting="chat"]');
await new Promise(resolve=>setTimeout(resolve,10));
assert.equal(app.state.chatOpen,true,'Gear opens the original staff chat');
let characterOpened=false,helpOpened=false;
w._swShowWardrobe=()=>{characterOpened=true;};w.__swShowHelp=()=>{helpOpened=true;};
click('[data-action="gear"]');click('[data-setting="character"]');assert(characterOpened);
click('[data-action="gear"]');click('[data-setting="help"]');assert(helpOpened);
click('[data-action="gear"]');click('[data-setting="controls"]');assert.equal(w.document.getElementById('sw-sens-panel').style.display,'block','Player controls opens the retained speed settings');click('#sw-sens-save');assert.equal(w.document.getElementById('sw-sens-panel').style.display,'none');
let roundsOpened=false,soundToggled=false;w.__swRounds=()=>{roundsOpened=true;};w.__swSoundToggle=()=>{soundToggled=true;};
click('[data-action="gear"]');click('[data-setting="rounds"]');await new Promise(r=>setTimeout(r,0));assert(roundsOpened);click('[data-action="gear"]');click('[data-setting="sound"]');assert(soundToggled);
let fullScreenOpened=false;w.document.documentElement.requestFullscreen=async()=>{fullScreenOpened=true;};click('[data-action="gear"]');click('[data-setting="fullscreen"]');await new Promise(r=>setTimeout(r,0));assert(fullScreenOpened);click('.close-dialog');
let reversed=false;w.__swReverseWalk=()=>{reversed=true;};click('[data-action="gear"]');click('[data-setting="reverse"]');assert(reversed&&w.__swDeckVisible===false,'Turn around outside returns to the property and reverses heading');await enter();
const locationBefore=app.walker.g.position.clone();
click('[data-action="exit"]');assert.equal(w.__swDeckVisible,false);
assert(app.walker.g.position.equals(locationBefore),'Leaving the room preserves the outdoor location');
assert.equal(app.state.chatOpen,false,'Staff chat closes when returning outside');
// Exercise the actual save boundary with a fake identity and fake network, never production.
app.state.editMode=true;w.__swCheckLogin=()=> 'Offline test';
const original=app._statusOf('G2');w.fetch=async()=>({ok:false});
assert.equal(await app.setStatus('G2','black'),false);assert.equal(app._statusOf('G2'),original,'Rejected save leaves unit status intact');
let writes=0,histories=0,alerts=0;
w.__swCommitLockChange=async(key,status,entry)=>{assert.equal(key,'G2');assert.equal(status,'black');assert.equal(entry.type,'lock');writes++;histories++;};
w.__swNotifyStatus=async(type,label)=>{assert.equal(type,'black');assert.equal(label,'G2');alerts++;};
await app.setStatus('G2','black');assert.equal(app._statusOf('G2'),'black');assert.equal(writes,1);assert.equal(histories,1,'Status and history share one confirmed save');assert.equal(alerts,1,'Confirmed save triggers a notification');
w.__swCommitLockChange=async()=>{throw new Error('offline failure');};await app.setStatus('G2','green');assert.equal(alerts,1,'Failed save never sends an alert');assert.equal(histories,1,'Failed save never records false history');
assert(!logs.some(x=>/SyntaxError|ReferenceError|TypeError/.test(x)),logs.join('\n'));
console.log(`PASS (${noGpu?'no GPU':'GPU renderer'}): ${Object.keys(app._locks).length} modeled units; original boot; search and filters; property location; room controls; mobile dock; save failure and success. No production writes.`);
dom.window.close();
}
await verifyContext(false);
await verifyContext(true);
sourceDom.window.close();
