// Delivery regression checks use only generated keys and intercepted provider requests.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {JSDOM} from 'jsdom';
import * as push from '../functions/notify.js';
import * as email from '../functions/email.js';
const originalFetch=globalThis.fetch;
const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);
const vapid=await crypto.subtle.exportKey('jwk',pair.privateKey);
const receiver=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);
const pub=Buffer.from(await crypto.subtle.exportKey('raw',receiver.publicKey)).toString('base64url');
const subscription=(name,endpoint,prefs)=>({staff:name,endpoint,keys:{p256dh:pub,auth:Buffer.from(crypto.getRandomValues(new Uint8Array(16))).toString('base64url')},...(prefs?{prefs}:{})});
const env={VAPID_PRIVATE_JWK:JSON.stringify(vapid),FIREBASE_DB_SECRET:'offline-test-secret',BREVO_API_KEY:'offline-test-provider'};
let requests=[];
globalThis.fetch=async(url,init={})=>{requests.push({url:String(url),init});if(String(url).includes('/pushSubs.json'))return Response.json({a:subscription('Kevin','https://fcm.googleapis.com/valid'),b:subscription('Mike','https://fcm.googleapis.com/disabled',{flashred:false}),c:subscription('Brad','https://fcm.googleapis.com/expired')});if(String(url).includes('/expired'))return new Response('',{status:410});return new Response('',{status:201});};
const request=d=>new Request('https://storewell.test/notify',{method:'POST',body:JSON.stringify(d)});
const health=await (await push.onRequestGet({env})).json();assert(health.configured&&health.publicKey);assert(!JSON.stringify(health).includes(vapid.d),'Health never reveals the private key');
let r=await push.onRequestPost({env,request:request({type:'flashred',title:'Lock It — G2',body:'Unit G2 by Kevin'})});let d=await r.json();
assert.equal(d.sent,1);assert.equal(d.failed,1);assert.equal(d.skipped,1);assert.equal(d.expired,1);
const send=requests.find(x=>x.url.endsWith('/valid'));assert(send);assert.equal(new Headers(send.init.headers).get('Content-Encoding'),'aes128gcm');assert(new Headers(send.init.headers).get('Authorization').startsWith('vapid '));assert(send.init.body.byteLength>1000,'Notification has an encrypted payload');assert(!Buffer.from(send.init.body).toString().includes('Unit G2'),'Message is not plaintext');assert(requests.some(x=>x.init.method==='DELETE'),'Expired subscriptions are cleaned');
requests=[];r=await push.onRequestPost({env,request:request({type:'report',title:'Report',recipients:['Kevin']})});d=await r.json();assert.equal(d.sent,1);assert(!requests.some(x=>x.url.endsWith('/expired')),'Reports honor selected staff recipients');
assert.equal((await push.onRequestPost({env:{},request:request({type:'report',title:'Report'})})).status,503);
globalThis.fetch=async()=>Response.json({code:'unauthorized'},{status:401});
r=await email.onRequestPost({env,request:request({to:'staff@example.test',body:'Report'})});assert.equal(r.status,502);assert.equal((await r.json()).success,false,'Provider rejection is an HTTP failure');
let payload;
globalThis.fetch=async(url,init)=>{payload=JSON.parse(init.body);return Response.json({messageId:'offline-message-id'},{status:201});};
r=await email.onRequestPost({env,request:request({to:'staff@example.test',body:'<script>unsafe</script>'})});assert.equal((await r.json()).messageId,'offline-message-id');assert(!payload.htmlContent.includes('<script>'),'Plain text HTML fallback is escaped');
// Exercise the real report modal: partial failures retain data and retry only pending recipients.
const dom=new JSDOM('<body></body>',{url:'https://storewell.test',runScripts:'outside-only'}),w=dom.window;
w.__swCheckLogin=()=>true;w.AbortSignal.timeout=()=>undefined;
const initial={label:'G2',from:'Rented',to:'Locked out',t:100};const newer={label:'G3',from:'Empty',to:'Rented',t:200};
w.__swApp={state:{sessionLog:[initial],staffName:'Offline test'},setState(v){Object.assign(this.state,v);}};
let emails=[],attempt=0;
w.fetch=async(url,init)=>{if(String(url).includes('staffConfig'))return {ok:true,json:async()=>({Kevin:{email:'kevin@example.test',pref:'email'},Mike:{email:'mike@example.test',pref:'email'},Brad:{pref:'none'}})};const to=JSON.parse(init.body).to;emails.push(to);const success=to!=='mike@example.test'||attempt>0;return {ok:success,json:async()=>({success,messageId:success?'test-message':undefined,error:'Provider offline'})};};
const staff=fs.readFileSync(new URL('../src/staff.js',import.meta.url),'utf8');
w.eval(staff.slice(staff.indexOf('async function _sendEmail('),staff.indexOf('\nfunction _toast(')));
w.eval(staff.slice(staff.indexOf('window.__swSaveReport=function(){'),staff.indexOf('// Joystick repositioning')));
w.__swSaveReport();await new Promise(r=>setTimeout(r,10));await w.document.querySelector('#sw-sr-send').onclick();
assert.equal(w.__swApp.state.sessionLog.length,1,'Email failure retains the report');assert(w.document.querySelector('#sw-sr-status').textContent.includes('Still pending'));
w.__swApp.state.sessionLog.push(newer);attempt++;await w.document.querySelector('#sw-sr-send').onclick();
assert.equal(emails.filter(e=>e==='kevin@example.test').length,1,'Retry does not duplicate an accepted email');assert.equal(emails.filter(e=>e==='mike@example.test').length,2);assert.equal(w.__swApp.state.sessionLog.length,1);assert.equal(w.__swApp.state.sessionLog[0],newer,'Finishing a report preserves changes made during delivery');
dom.window.close();
// The service worker displays the actual event payload rather than a shared database record.
const events={},shown=[];const scope={addEventListener:(name,fn)=>events[name]=fn,registration:{showNotification:async(...args)=>shown.push(args)}};
vm.runInNewContext(fs.readFileSync(new URL('../public/sw.js',import.meta.url),'utf8'),{self:scope,URL,Response});
let pending;events.push({data:{json:()=>({title:'Unit C12',body:'Lock removed',tag:'test-1'})},waitUntil:p=>pending=p});await pending;assert.equal(shown[0][0],'Unit C12');assert.equal(shown[0][1].body,'Lock removed');
globalThis.fetch=originalFetch;
console.log('PASS: encrypted push payloads, device preferences, selected recipients, expired subscriptions, truthful email failures, retry preservation and service worker messages. No live messages sent.');
